# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e386cad08ab222ba88c13cb939db31509adaf662efff537cc0ef9a57f0b4a3ca3072ecc7cd85998fe1c99681790eb221060d0b88dfed1fc69aa62c9165aca02f

test:
  secret_key_base: 5bf2d061c19a159f198030b636b80d70cc8c6036c8713f246a21c414d57b04a8e369a7c798a3d03e92a342f03d66dae8ffd056c29ae5e0b9606e94cd14d14301

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
